# Generated by Django 5.1.3 on 2025-04-05 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRobinhoodInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=2000)),
                ('refresh_token', models.CharField(max_length=255)),
                ('device_token', models.CharField(max_length=255)),
                ('issued_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('args', models.JSONField()),
                ('response', models.JSONField()),
                ('status', models.IntegerField()),
                ('success', models.BooleanField()),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rh_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'success', 'status'], name='robin_stock_date_f2c02b_idx'), models.Index(fields=['user', 'date', 'success', 'status'], name='robin_stock_user_id_98d467_idx')],
            },
        ),
    ]
