# Generated by Django 5.2.1 on 2025-05-21 05:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAnon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('method', models.CharField()),
                ('user', models.CharField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('errors', models.JSONField(default=None, null=True)),
                ('state', models.CharField()),
                ('status', models.IntegerField()),
                ('pre_account_id', models.CharField(default=None, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'status', 'state'], name='robin_stock_date_6ad914_idx'), models.Index(fields=['user', 'date', 'status', 'state'], name='robin_stock_user_ae7e3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRobinhoodInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(max_length=255)),
                ('_access_token', models.BinaryField()),
                ('access_token_dek', models.BinaryField()),
                ('_refresh_token', models.BinaryField()),
                ('refresh_token_dek', models.BinaryField()),
                ('_device_token', models.BinaryField()),
                ('device_token_dek', models.BinaryField()),
                ('issued_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_time', models.DateTimeField()),
                ('previousRefreshSuccess', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('method', models.CharField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('errors', models.JSONField(default=None, null=True)),
                ('state', models.CharField()),
                ('status', models.IntegerField()),
                ('pre_account_id', models.PositiveIntegerField(default=None, null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'status', 'state'], name='robin_stock_date_899562_idx'), models.Index(fields=['user', 'date', 'status', 'state'], name='robin_stock_user_id_414d82_idx')],
            },
        ),
    ]
