# Generated by Django 5.1.3 on 2025-01-08 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robin_stocks', '0002_alter_userrobinhoodinfo_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrobinhoodinfo',
            name='expiration_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userrobinhoodinfo',
            name='issued_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
