# Generated by Django 5.1.3 on 2025-01-09 00:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robin_stocks', '0003_userrobinhoodinfo_expiration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrobinhoodinfo',
            name='issued_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
