# Generated by Django 5.1.3 on 2025-03-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robin_stocks', '0004_alter_userrobinhoodinfo_issued_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('user', models.DateTimeField(default=None, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('args', models.JSONField()),
                ('response', models.JSONField()),
                ('status', models.IntegerField()),
                ('success', models.BooleanField()),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'success', 'status'], name='robin_stock_date_f2c02b_idx'), models.Index(fields=['user', 'date', 'success', 'status'], name='robin_stock_user_643b60_idx')],
            },
        ),
    ]
